import { env } from "./env";

export const serverConfig = {
  PORT: env.PORT,
  NODE_ENV: env.NODE_ENV,
  MCP_SERVER_PORT: env.MCP_SERVER_PORT,
  APP_NAME: env.APP_NAME,
  DB_URL: env.DB_URL,
  REDIS_URL: env.REDIS_URL,
  BASE_URL: env.BASE_URL,

  ANALYTICS_QUEUE: env.ANALYTICS_QUEUE,
  ANALYTICS_DEAD_LETTER_QUEUE: env.ANALYTICS_DEAD_LETTER_QUEUE,

  REDIS_COUNTER_KEY: env.REDIS_COUNTER_KEY,

  JWT_ACCESS_SECRET: env.JWT_ACCESS_SECRET,
  JWT_REFRESH_SECRET: env.JWT_REFRESH_SECRET,

  ACCESS_TOKEN_EXPIRE: env.ACCESS_TOKEN_EXPIRE,
  REFRESH_TOKEN_EXPIRE: env.REFRESH_TOKEN_EXPIRE,

  URL_EXPIRY_SCHEDULER: env.URL_EXPIRY_SCHEDULER,
  AGGREGATION_ANALYTICS_SCHEDULER: env.AGGREGATION_ANALYTICS_SCHEDULER,

  EMAIL_TRANSPORTER: env.EMAIL_TRANSPORTER,

  SMTP_HOST: env.SMTP_HOST,
  SMTP_PORT: env.SMTP_PORT,
  SMTP_SECURE: env.SMTP_SECURE,
  SMTP_USER: env.SMTP_USER,
  SMTP_PASS: env.SMTP_PASS,

  EMAIL_FROM_ADDRESS: env.EMAIL_FROM_ADDRESS,
  EMAIL_FROM_NAME: env.EMAIL_FROM_NAME,
  EMAIL_TEMPLATES_PATH: env.EMAIL_TEMPLATES_PATH,

  VERIFICATION_TOKEN_EXPIRE: env.VERIFICATION_TOKEN_EXPIRE,
  RESET_TOKEN_EXPIRE: env.RESET_TOKEN_EXPIRE,

  EMAIL_REQUEST_RATE_LIMIT: env.EMAIL_REQUEST_RATE_LIMIT,

  CLIENT_URL: env.CLIENT_URL,
  
  // Server configuration
  SERVER_TIMEOUT: env.SERVER_TIMEOUT,
  KEEP_ALIVE_TIMEOUT: env.KEEP_ALIVE_TIMEOUT,
  HEADERS_TIMEOUT: env.HEADERS_TIMEOUT,
  MAX_CONNECTIONS: env.MAX_CONNECTIONS,
  
  // Health check configuration
  HEALTH_CHECK_TIMEOUT: env.HEALTH_CHECK_TIMEOUT,
  
  // CORS configuration
  CORS_ORIGINS: env.CORS_ORIGINS,
  APP_VERSION: env.APP_VERSION,
};
