FROM node:lts-alpine3.22 AS development

WORKDIR /server

COPY package*.json ./
RUN npm ci

# Install dev dependencies
RUN npm install --save-dev nodemon ts-node

COPY . .

EXPOSE 4000

CMD ["npm", "run", "dev"]